x-default-isaac-lab-devcontainer-environment: &default-isaac-lab-devcontainer-environment
  - OMNI_KIT_ALLOW_ROOT=1
  - DISPLAY=:0
  - TERM=xterm-256color
  - SHELL=zsh
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US:en
  - LC_ALL=en_US.UTF-8

x-default-isaac-lab-devcontainer-deploy: &default-isaac-lab-devcontainer-deploy
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: all
          capabilities: [ gpu ]

services:
  isaac-lab-devcontainer:
    env_file: .env.base
    image: nvcr.io/nvidia/isaac-sim:4.5.0
    container_name: isaac-lab-devcontainer
    volumes:
      - type: bind
        source: ../
        target: /home/ubuntu/isaac-lab-devcontainer
    network_mode: host
    environment: *default-isaac-lab-devcontainer-environment
    deploy: *default-isaac-lab-devcontainer-deploy
    # This is the entrypoint for the container
    entrypoint: bash
    stdin_open: true
    tty: true
